### ISSUE TITLE
[BUG] Block Particles not working

### ISSUE THREAD

**Issue by Fair3192** [SkriptHub/SkBee#10]
### What happened?

When i use this command !make 1 of block particle using dirt at location of target block
nothing happens

### Steps to reproduce

1. run !make 1 of block particle using dirt at location of target block
2. then look at target block
3. you see nothing there

### Expected behavior

i expected to see block particles but i see nothing

### SkBee Version

3.6.3

### Server Version

Paper 1.21.1

### SkBee Info

[CHAT] --- [SkBee Loading Info] ---
[CHAT] - [NBTAPI] Found Minecraft: 1.21.1! Trying to find NMS support
[CHAT] - [NBTAPI] NMS support 'MC1_21_R1' loaded!
[CHAT] - NBT Elements successfully loaded
[CHAT] - Text Component Elements successfully loaded
[CHAT] - Advancement Elements successfully loaded
[CHAT] - BossBar Elements successfully loaded
[CHAT] - Bound Elements successfully loaded
[CHAT] - Damage Source elements successfully loaded
[CHAT] - Display Entity elements successfully loaded
[CHAT] - Fishing elements successfully loaded
[CHAT] - Game Event Elements successfully loaded
[CHAT] - Item Component Elements successfully loaded
[CHAT] - Particle Elements successfully loaded
[CHAT] - RayTrace elements successfully loaded
[CHAT] - Recipe Elements successfully loaded
[CHAT] - Scoreboard Elements successfully loaded
[CHAT] - Scoreboard Objective Elements successfully loaded
[CHAT] - Statistic Elements successfully loaded
[CHAT] - Structure Elements successfully loaded
[CHAT] - Minecraft Tag elements successfully loaded
[CHAT] - Team Elements successfully loaded
[CHAT] - Tick Manager elements successfully loaded
[CHAT] - Villager Elements successfully loaded
[CHAT] - Virtual Furnace Elements disabled via config
[CHAT] - World Border Elements successfully loaded
[CHAT] - World Creator Elements successfully loaded
[CHAT] - Chunk Generator Elements disabled via config
[CHAT] - Plugin is up to date!
[CHAT] --- [Server Info] ---
[CHAT] Server Version: 1.21.1-131-84281ce (MC: 1.21.1)
[CHAT] Skript Version: 2.9.3
[CHAT] Skript Addons:
[CHAT] - Skellett v2.0.10
[CHAT] - skript-reflect v2.5.1
[CHAT] SkBee Version: 3.6.3
[CHAT] SkBee Website: https://github.com/SkriptHub/SkBee

**Comment by ShaneBeee** [comment]
This is an odd one, this has never given issue before.
I wonder if Skript changed something that makes this error now.
Anyways, PR has been done to fix it #11

**Comment by Fair3192** [comment]
Thanks
