### ISSUE TITLE
[BUG] Using the syntax ‘block data tag’ will result in unusually long reload times. 

### ISSUE THREAD

**Issue by Radiation-pi** [SkriptHub/SkBee#15]
### What happened?

Using syntax ‘block data tag’ will take much more time to reload than syntax ‘blockdata tag

Just a space make it so different, which is confusing but interesting

### Steps to reproduce

I have a script like this:

```skript
# doubledoor
on right click on any door:
    loop (block south of block),(block north of block),(block east of block),(block west of block):
        (block data tag "hinge" of loop-value) != (block data tag "hinge" of block)
        (block data tag "open" of loop-value) = (block data tag "open" of block)
        (block data tag "facing" of loop-value) = (block data tag "facing" of block)
        toggle loop-value
        stop
```

So player can open both door when the right click a door, it's easy to understand.

Then I updata to skript 2.10.0-beta1 and Skbee 3.6.4. (From skript 2.9.4)
 
Then it will cost 20x more time to reload this script, The more you use the syntax ‘block data tag’, the longer it will take to reload.

### Expected behavior

It will cost a little ms to reload.

### SkBee Version

3.6.4(lastest)

### Server Version

paper 1.21.1

### SkBee Info

[12:06:14 INFO]: --- [Server Info] ---
[12:06:14 INFO]: Server Version: 1.21.1-DEV-3ed6b80 (MC: 1.21.1)
[12:06:14 INFO]: Skript Version: 2.10.0-beta1
[12:06:14 INFO]: Skript Addons:
[12:06:14 INFO]: - skript-placeholders v1.6.0
[12:06:14 INFO]: - skript-itemsadder v1.6.1
[12:06:14 INFO]: - skript-reflect v2.5.1
[12:06:14 INFO]: - skript-db v1.4.0
[12:06:14 INFO]: - skript-worldedit v1.1.2
[12:06:14 INFO]: - Skript-Packet v2.2.2
[12:06:14 INFO]: - RediSkript v1.3.7-SNAPSHOT
[12:06:14 INFO]: - ItemsAdder v4.0.3
[12:06:14 INFO]: - MythicSkriptAddon v0.99.7
[12:06:14 INFO]: SkBee Version: 3.6.4
[12:06:14 INFO]: SkBee Website: https://github.com/SkriptHub/SkBee

### Additional Information

This isn't a problem for me now, but some servers that make heavy use of this syntax can take a lot of time or even cause the server to crash when reloading scripts

Besides, there is a little benchmark:
```
block data tag "open" of loop-value = block data tag "open" of block * 100 rows script reload takes 60s (server crashed)

(block data tag "open" of loop-value) = (block data tag "open" of block) * 100 rows script reload takes 1500ms

(blockdata tag "open" of loop-value) = (blockdata tag "open" of block) * 100 rows script reload takes 60ms

**Comment by ShaneBeee** [comment]
This isn't a bug, as much as this is just how bad Skript is at parsing expressions.
From an add-on, theres really nothing we can do here to fix parsing issues.
Skript itself is just as bad with its own stuff.
Ex:
`1 of diamond sword of unbreaking 3 = diamond sword of unbreaking` * 100 = 405ms parsing

That said, Skript has stated for a long time, to break up parsing time use parenthesis, which I see you already know, so you've already been able to fix your issue.

Sorry I have to said it, but theres really nothing I can do here.
