### ISSUE TITLE
[BUG] Item flag hide attributes not working properly

### ISSUE THREAD

**Issue by sluhtie** [SkriptHub/SkBee#21]
### What happened?

The hide attributes flag does not work

### Steps to reproduce

1. Take any Item like an Sword for example
2. Apply the item flag hide attributes or all item flags. Example: `!set tool of me to tool of me with item flag hide attributes`
3. You will see that the attributes will still be visible

### Expected behavior

That the hide attributes flag actually hides the attributes.

### SkBee Version

2.6.5

### Server Version

Purpur 1.21.1 Build Latest

### SkBee Info

![image](https://github.com/user-attachments/assets/c4345d97-3e31-49ce-b9d1-920e97b0f77a)

**Comment by ShaneBeee** [comment]
This is actually a quirk with Minecraft.
To apply the flag, you need to supply a new list of attribute modifiers.
Unfortunately it wont work on the vanilla attribute modifiers.

I made a post in the SkBee wiki regarding this:
https://github.com/ShaneBeee/SkBee/wiki/Tricks-Hide-Attribute-Modifiers
